// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type LaelActivityLogsActivityType string

const (
	LaelActivityLogsActivityTypeLogin           LaelActivityLogsActivityType = "login"
	LaelActivityLogsActivityTypeLogout          LaelActivityLogsActivityType = "logout"
	LaelActivityLogsActivityTypePatientCreation LaelActivityLogsActivityType = "patient_creation"
	LaelActivityLogsActivityTypeStaffApproval   LaelActivityLogsActivityType = "staff_approval"
	LaelActivityLogsActivityTypeOpdGeneration   LaelActivityLogsActivityType = "opd_generation"
)

func (e *LaelActivityLogsActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaelActivityLogsActivityType(s)
	case string:
		*e = LaelActivityLogsActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for LaelActivityLogsActivityType: %T", src)
	}
	return nil
}

type NullLaelActivityLogsActivityType struct {
	LaelActivityLogsActivityType LaelActivityLogsActivityType `json:"lael_activity_logs_activity_type"`
	Valid                        bool                         `json:"valid"` // Valid is true if LaelActivityLogsActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaelActivityLogsActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.LaelActivityLogsActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaelActivityLogsActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaelActivityLogsActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaelActivityLogsActivityType), nil
}

type LaelOtpOtpType string

const (
	LaelOtpOtpTypeRegistration   LaelOtpOtpType = "registration"
	LaelOtpOtpTypeLogin          LaelOtpOtpType = "login"
	LaelOtpOtpTypeForgotPassword LaelOtpOtpType = "forgot_password"
)

func (e *LaelOtpOtpType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaelOtpOtpType(s)
	case string:
		*e = LaelOtpOtpType(s)
	default:
		return fmt.Errorf("unsupported scan type for LaelOtpOtpType: %T", src)
	}
	return nil
}

type NullLaelOtpOtpType struct {
	LaelOtpOtpType LaelOtpOtpType `json:"lael_otp_otp_type"`
	Valid          bool           `json:"valid"` // Valid is true if LaelOtpOtpType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaelOtpOtpType) Scan(value interface{}) error {
	if value == nil {
		ns.LaelOtpOtpType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaelOtpOtpType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaelOtpOtpType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaelOtpOtpType), nil
}

type LaelPatientsSex string

const (
	LaelPatientsSexMale   LaelPatientsSex = "male"
	LaelPatientsSexFemale LaelPatientsSex = "female"
	LaelPatientsSexOther  LaelPatientsSex = "other"
)

func (e *LaelPatientsSex) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaelPatientsSex(s)
	case string:
		*e = LaelPatientsSex(s)
	default:
		return fmt.Errorf("unsupported scan type for LaelPatientsSex: %T", src)
	}
	return nil
}

type NullLaelPatientsSex struct {
	LaelPatientsSex LaelPatientsSex `json:"lael_patients_sex"`
	Valid           bool            `json:"valid"` // Valid is true if LaelPatientsSex is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaelPatientsSex) Scan(value interface{}) error {
	if value == nil {
		ns.LaelPatientsSex, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaelPatientsSex.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaelPatientsSex) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaelPatientsSex), nil
}

type LaelUsersDesignation string

const (
	LaelUsersDesignationDoctor LaelUsersDesignation = "doctor"
	LaelUsersDesignationNurse  LaelUsersDesignation = "nurse"
	LaelUsersDesignationStaff  LaelUsersDesignation = "staff"
)

func (e *LaelUsersDesignation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaelUsersDesignation(s)
	case string:
		*e = LaelUsersDesignation(s)
	default:
		return fmt.Errorf("unsupported scan type for LaelUsersDesignation: %T", src)
	}
	return nil
}

type NullLaelUsersDesignation struct {
	LaelUsersDesignation LaelUsersDesignation `json:"lael_users_designation"`
	Valid                bool                 `json:"valid"` // Valid is true if LaelUsersDesignation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaelUsersDesignation) Scan(value interface{}) error {
	if value == nil {
		ns.LaelUsersDesignation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaelUsersDesignation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaelUsersDesignation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaelUsersDesignation), nil
}

type LaelUsersStatus string

const (
	LaelUsersStatusActive            LaelUsersStatus = "active"
	LaelUsersStatusInactive          LaelUsersStatus = "inactive"
	LaelUsersStatusTemporaryInactive LaelUsersStatus = "temporary_inactive"
)

func (e *LaelUsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaelUsersStatus(s)
	case string:
		*e = LaelUsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LaelUsersStatus: %T", src)
	}
	return nil
}

type NullLaelUsersStatus struct {
	LaelUsersStatus LaelUsersStatus `json:"lael_users_status"`
	Valid           bool            `json:"valid"` // Valid is true if LaelUsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaelUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LaelUsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaelUsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaelUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaelUsersStatus), nil
}

type LaelActivityLog struct {
	ID           int64                        `json:"id"`
	UserID       sql.NullInt64                `json:"user_id"`
	ActivityType LaelActivityLogsActivityType `json:"activity_type"`
	Description  sql.NullString               `json:"description"`
	IpAddress    sql.NullString               `json:"ip_address"`
	CreatedOn    time.Time                    `json:"created_on"`
}

type LaelOtp struct {
	ID          int64          `json:"id"`
	Mobile      string         `json:"mobile"`
	Otp         string         `json:"otp"`
	Expiry      time.Time      `json:"expiry"`
	IsValidated bool           `json:"is_validated"`
	OtpType     LaelOtpOtpType `json:"otp_type"`
	RetryCount  int32          `json:"retry_count"`
	CreatedOn   time.Time      `json:"created_on"`
	UpdatedOn   time.Time      `json:"updated_on"`
}

type LaelPatient struct {
	ID              int64           `json:"id"`
	Name            string          `json:"name"`
	Mobile          string          `json:"mobile"`
	OpdID           string          `json:"opd_id"`
	Age             int32           `json:"age"`
	Sex             LaelPatientsSex `json:"sex"`
	AddressLocality sql.NullString  `json:"address_locality"`
	AddressCity     sql.NullString  `json:"address_city"`
	AddressState    sql.NullString  `json:"address_state"`
	AddressPincode  sql.NullString  `json:"address_pincode"`
	VisitNumber     int32           `json:"visit_number"`
	CreatedOn       time.Time       `json:"created_on"`
	UpdatedOn       time.Time       `json:"updated_on"`
}

type LaelSession struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	SessionToken  string         `json:"session_token"`
	SessionExpiry time.Time      `json:"session_expiry"`
	LastActiveAt  time.Time      `json:"last_active_at"`
	DeviceInfo    sql.NullString `json:"device_info"`
	IpAddress     sql.NullString `json:"ip_address"`
	CreatedOn     time.Time      `json:"created_on"`
}

type LaelUser struct {
	ID           int64                `json:"id"`
	Name         string               `json:"name"`
	Mobile       string               `json:"mobile"`
	Email        sql.NullString       `json:"email"`
	Designation  LaelUsersDesignation `json:"designation"`
	Status       LaelUsersStatus      `json:"status"`
	IsAdmin      bool                 `json:"is_admin"`
	IsApproved   bool                 `json:"is_approved"`
	ApprovedBy   sql.NullInt64        `json:"approved_by"`
	PasswordHash sql.NullString       `json:"password_hash"`
	CreatedOn    time.Time            `json:"created_on"`
	UpdatedOn    time.Time            `json:"updated_on"`
	LastLoginAt  sql.NullTime         `json:"last_login_at"`
}

type PatientOpd struct {
	ID               int64           `json:"id"`
	PatientID        int64           `json:"patient_id"`
	DoctorID         int64           `json:"doctor_id"`
	Symptoms         json.RawMessage `json:"symptoms"`
	Prescription     json.RawMessage `json:"prescription"`
	Medicines        json.RawMessage `json:"medicines"`
	FutureSuggestion json.RawMessage `json:"future_suggestion"`
	TemplateVersion  int32           `json:"template_version"`
	CreatedOn        time.Time       `json:"created_on"`
	UpdatedOn        time.Time       `json:"updated_on"`
}
