// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: otp.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createOTP = `-- name: CreateOTP :execresult
INSERT INTO lael_otp (
    mobile, otp, expiry, otp_type, retry_count
) VALUES (?, ?, ?, ?, 0)
`

type CreateOTPParams struct {
	Mobile  string         `json:"mobile"`
	Otp     string         `json:"otp"`
	Expiry  time.Time      `json:"expiry"`
	OtpType LaelOtpOtpType `json:"otp_type"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOTP,
		arg.Mobile,
		arg.Otp,
		arg.Expiry,
		arg.OtpType,
	)
}

const deleteExpiredOTP = `-- name: DeleteExpiredOTP :exec
DELETE FROM lael_otp
WHERE expiry < NOW()
`

func (q *Queries) DeleteExpiredOTP(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOTP)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, mobile, otp, expiry, is_validated, otp_type, retry_count, created_on, updated_on FROM lael_otp
WHERE mobile = ? AND otp_type = ? AND is_validated = FALSE
ORDER BY created_on DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Mobile  string         `json:"mobile"`
	OtpType LaelOtpOtpType `json:"otp_type"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (LaelOtp, error) {
	row := q.db.QueryRowContext(ctx, getLatestOTP, arg.Mobile, arg.OtpType)
	var i LaelOtp
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.Otp,
		&i.Expiry,
		&i.IsValidated,
		&i.OtpType,
		&i.RetryCount,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const incrementRetryCount = `-- name: IncrementRetryCount :exec
UPDATE lael_otp
SET retry_count = retry_count + 1, updated_on = NOW()
WHERE id = ?
`

func (q *Queries) IncrementRetryCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementRetryCount, id)
	return err
}

const validateOTP = `-- name: ValidateOTP :exec
UPDATE lael_otp
SET is_validated = TRUE, updated_on = NOW()
WHERE id = ?
`

func (q *Queries) ValidateOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, validateOTP, id)
	return err
}
