// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPatient = `-- name: CreatePatient :execresult
INSERT INTO lael_patients (
    name, mobile, opd_id, age, sex,
    address_locality, address_city, address_state, address_pincode,
    visit_number
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePatientParams struct {
	Name            string          `json:"name"`
	Mobile          string          `json:"mobile"`
	OpdID           string          `json:"opd_id"`
	Age             int32           `json:"age"`
	Sex             LaelPatientsSex `json:"sex"`
	AddressLocality sql.NullString  `json:"address_locality"`
	AddressCity     sql.NullString  `json:"address_city"`
	AddressState    sql.NullString  `json:"address_state"`
	AddressPincode  sql.NullString  `json:"address_pincode"`
	VisitNumber     int32           `json:"visit_number"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPatient,
		arg.Name,
		arg.Mobile,
		arg.OpdID,
		arg.Age,
		arg.Sex,
		arg.AddressLocality,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPincode,
		arg.VisitNumber,
	)
}

const getAllVisitsByMobile = `-- name: GetAllVisitsByMobile :many
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE mobile = ?
ORDER BY visit_number ASC
`

func (q *Queries) GetAllVisitsByMobile(ctx context.Context, mobile string) ([]LaelPatient, error) {
	rows, err := q.db.QueryContext(ctx, getAllVisitsByMobile, mobile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelPatient{}
	for rows.Next() {
		var i LaelPatient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mobile,
			&i.OpdID,
			&i.Age,
			&i.Sex,
			&i.AddressLocality,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPincode,
			&i.VisitNumber,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVisitByOPDID = `-- name: GetLatestVisitByOPDID :one
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE opd_id = ?
ORDER BY visit_number DESC
`

func (q *Queries) GetLatestVisitByOPDID(ctx context.Context, opdID string) (LaelPatient, error) {
	row := q.db.QueryRowContext(ctx, getLatestVisitByOPDID, opdID)
	var i LaelPatient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mobile,
		&i.OpdID,
		&i.Age,
		&i.Sex,
		&i.AddressLocality,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPincode,
		&i.VisitNumber,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients WHERE id = ?
`

func (q *Queries) GetPatientByID(ctx context.Context, id int64) (LaelPatient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByID, id)
	var i LaelPatient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mobile,
		&i.OpdID,
		&i.Age,
		&i.Sex,
		&i.AddressLocality,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPincode,
		&i.VisitNumber,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getPatientByMobile = `-- name: GetPatientByMobile :one
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE mobile = ?
ORDER BY created_on DESC
LIMIT 1
`

func (q *Queries) GetPatientByMobile(ctx context.Context, mobile string) (LaelPatient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByMobile, mobile)
	var i LaelPatient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mobile,
		&i.OpdID,
		&i.Age,
		&i.Sex,
		&i.AddressLocality,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPincode,
		&i.VisitNumber,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getPatientByOPDID = `-- name: GetPatientByOPDID :one
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients WHERE opd_id = ?
`

func (q *Queries) GetPatientByOPDID(ctx context.Context, opdID string) (LaelPatient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByOPDID, opdID)
	var i LaelPatient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mobile,
		&i.OpdID,
		&i.Age,
		&i.Sex,
		&i.AddressLocality,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPincode,
		&i.VisitNumber,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getPatientsByDateRange = `-- name: GetPatientsByDateRange :many
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE created_on BETWEEN ? AND ?
ORDER BY created_on DESC
LIMIT ? OFFSET ?
`

type GetPatientsByDateRangeParams struct {
	FromCreatedOn time.Time `json:"from_created_on"`
	ToCreatedOn   time.Time `json:"to_created_on"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) GetPatientsByDateRange(ctx context.Context, arg GetPatientsByDateRangeParams) ([]LaelPatient, error) {
	rows, err := q.db.QueryContext(ctx, getPatientsByDateRange,
		arg.FromCreatedOn,
		arg.ToCreatedOn,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelPatient{}
	for rows.Next() {
		var i LaelPatient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mobile,
			&i.OpdID,
			&i.Age,
			&i.Sex,
			&i.AddressLocality,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPincode,
			&i.VisitNumber,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayPatients = `-- name: GetTodayPatients :many
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE DATE(created_on) = CURDATE()
ORDER BY created_on DESC
`

func (q *Queries) GetTodayPatients(ctx context.Context) ([]LaelPatient, error) {
	rows, err := q.db.QueryContext(ctx, getTodayPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelPatient{}
	for rows.Next() {
		var i LaelPatient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mobile,
			&i.OpdID,
			&i.Age,
			&i.Sex,
			&i.AddressLocality,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPincode,
			&i.VisitNumber,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatientsByMobile = `-- name: SearchPatientsByMobile :many
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE mobile LIKE ?
ORDER BY created_on DESC
LIMIT ? OFFSET ?
`

type SearchPatientsByMobileParams struct {
	Mobile string `json:"mobile"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchPatientsByMobile(ctx context.Context, arg SearchPatientsByMobileParams) ([]LaelPatient, error) {
	rows, err := q.db.QueryContext(ctx, searchPatientsByMobile, arg.Mobile, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelPatient{}
	for rows.Next() {
		var i LaelPatient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mobile,
			&i.OpdID,
			&i.Age,
			&i.Sex,
			&i.AddressLocality,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPincode,
			&i.VisitNumber,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatientsByName = `-- name: SearchPatientsByName :many
SELECT id, name, mobile, opd_id, age, sex, address_locality, address_city, address_state, address_pincode, visit_number, created_on, updated_on FROM lael_patients
WHERE name LIKE ?
ORDER BY created_on DESC
LIMIT ? OFFSET ?
`

type SearchPatientsByNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]LaelPatient, error) {
	rows, err := q.db.QueryContext(ctx, searchPatientsByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelPatient{}
	for rows.Next() {
		var i LaelPatient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mobile,
			&i.OpdID,
			&i.Age,
			&i.Sex,
			&i.AddressLocality,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPincode,
			&i.VisitNumber,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientVisitNumber = `-- name: UpdatePatientVisitNumber :exec
UPDATE lael_patients
SET visit_number = visit_number + 1, updated_on = NOW()
WHERE mobile = ?
`

func (q *Queries) UpdatePatientVisitNumber(ctx context.Context, mobile string) error {
	_, err := q.db.ExecContext(ctx, updatePatientVisitNumber, mobile)
	return err
}
