// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ApproveStaff(ctx context.Context, arg ApproveStaffParams) error
	CreateOTP(ctx context.Context, arg CreateOTPParams) (sql.Result, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (sql.Result, error)
	CreatePatientOPD(ctx context.Context, arg CreatePatientOPDParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteExpiredOTP(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, sessionToken string) error
	GetAllVisitsByMobile(ctx context.Context, mobile string) ([]LaelPatient, error)
	GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (LaelOtp, error)
	GetLatestOTPByEmail(ctx context.Context, arg GetLatestOTPByEmailParams) (LaelOtp, error)
	GetLatestPatientOPD(ctx context.Context, patientID int64) (PatientOpd, error)
	GetLatestVisitByOPDID(ctx context.Context, opdID string) (LaelPatient, error)
	GetPatientByID(ctx context.Context, id int64) (LaelPatient, error)
	GetPatientByMobile(ctx context.Context, mobile string) (LaelPatient, error)
	GetPatientByOPDID(ctx context.Context, opdID string) (LaelPatient, error)
	GetPatientOPDByID(ctx context.Context, id int64) (PatientOpd, error)
	GetPatientOPDsByDoctor(ctx context.Context, arg GetPatientOPDsByDoctorParams) ([]GetPatientOPDsByDoctorRow, error)
	GetPatientOPDsByPatientID(ctx context.Context, patientID int64) ([]PatientOpd, error)
	GetPatientsByDateRange(ctx context.Context, arg GetPatientsByDateRangeParams) ([]LaelPatient, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (LaelSession, error)
	GetTodayPatients(ctx context.Context) ([]LaelPatient, error)
	GetUserByEmail(ctx context.Context, email string) (LaelUser, error)
	GetUserByID(ctx context.Context, id int64) (LaelUser, error)
	GetUserByMobile(ctx context.Context, mobile string) (LaelUser, error)
	GetUserSessions(ctx context.Context, userID int64) ([]LaelSession, error)
	IncrementRetryCount(ctx context.Context, id int64) error
	ListPendingStaffApprovals(ctx context.Context) ([]LaelUser, error)
	ListStaffByStatus(ctx context.Context, arg ListStaffByStatusParams) ([]LaelUser, error)
	SearchPatientsByMobile(ctx context.Context, arg SearchPatientsByMobileParams) ([]LaelPatient, error)
	SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]LaelPatient, error)
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdatePatientVisitNumber(ctx context.Context, mobile string) error
	UpdateSessionActivity(ctx context.Context, sessionToken string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	ValidateOTP(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
