// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO lael_sessions (
    user_id, session_token, session_expiry, device_info, ip_address
) VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	UserID        int64          `json:"user_id"`
	SessionToken  string         `json:"session_token"`
	SessionExpiry time.Time      `json:"session_expiry"`
	DeviceInfo    sql.NullString `json:"device_info"`
	IpAddress     sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.UserID,
		arg.SessionToken,
		arg.SessionExpiry,
		arg.DeviceInfo,
		arg.IpAddress,
	)
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM lael_sessions WHERE session_expiry < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM lael_sessions WHERE session_token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionToken)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, session_token, session_expiry, last_active_at, device_info, ip_address, created_on FROM lael_sessions WHERE session_token = ?
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (LaelSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, sessionToken)
	var i LaelSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.SessionExpiry,
		&i.LastActiveAt,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedOn,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, session_token, session_expiry, last_active_at, device_info, ip_address, created_on FROM lael_sessions
WHERE user_id = ?
ORDER BY last_active_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID int64) ([]LaelSession, error) {
	rows, err := q.db.QueryContext(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaelSession{}
	for rows.Next() {
		var i LaelSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionToken,
			&i.SessionExpiry,
			&i.LastActiveAt,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE lael_sessions
SET last_active_at = NOW()
WHERE session_token = ?
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, sessionToken)
	return err
}
